version: '3'

services:
  spark-master:
    container_name: spark-master
    hostname: spark-master
    # image: bitnami/spark:latest
    build:
      context: .
      dockerfile: Dockerfile.spark
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./config:/opt/bitnami/spark/config
      - ./datasets:/opt/bitnami/spark/datasets
      - ./requirements.txt:/requirements.txt
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - yelp-network

  spark-worker: &worker
    container_name: spark-worker
    hostname: spark-worker
    # image: bitnami/spark:latest
    build:
      context: .
      dockerfile: Dockerfile.spark
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
      - ./config:/opt/bitnami/spark/config
      - ./datasets:/opt/bitnami/spark/datasets
      - ./requirements.txt:/requirements.txt
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - yelp-network

  # spark-worker-2:
  #   <<: *worker

  # spark-worker-3:
  #   <<: *worker


networks:
  yelp-network: